; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:viewe_2_8]
platform = espressif32@6.9.0
board = lolin_s3_pro
framework = arduino
monitor_speed = 115200
lib_deps = 
	moononournation/GFX Library for Arduino@1.5.7
	lewisxhe/SensorLib@0.3.3
	lvgl/lvgl@9.4.0
	kitesurfer1404/WS2812FX@1.4.5
	bblanchon/ArduinoJson@7.3.0
	; file://./../../../LVGL-Editor/viewe_ui
build_flags = 
    -D LV_USE_OBJ_NAME=1
    -D LV_CONF_INCLUDE_SIMPLE
    -I include
